format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/accessom2_restart.nml
  hashes:
    binhash: 66c5aa3b79e56ab275b57020287155a0
    md5: 015f306fef2394266f674cb3c8064b8b
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/grid.nc
  hashes:
    binhash: f3dc7debc2f9e98a7f5102aa8c96af67
    md5: 1213e346055ee073fe33dc12578d99c6
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/i2o.nc
  hashes:
    binhash: 56ea4820a150ce344d2d96546524f3d7
    md5: 18d7737f4534d6441b34f7bad0bdc77c
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/ice.restart_file
  hashes:
    binhash: 9649a377978c21c8d595f47108700362
    md5: f5cafe3ef0a29dc462d0a84b80a9d20a
work/ice/RESTART/iced.1982-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/iced.1982-01-01-00000.nc
  hashes:
    binhash: d7f64c38ef4a5d3609cbb5f80f053000
    md5: 6355063e90f522c9cc974c4e1a61b9bd
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/kmt.nc
  hashes:
    binhash: 0ac50e0a0e02a9c901f124f22244fb33
    md5: 1f9806c646a620378e5257e480bc9df7
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/monthly_sstsss.nc
  hashes:
    binhash: 3b9d7589852b581a67eb78ad23ae9619
    md5: 323d4c605f83f4d7d3126da70153c2ed
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/o2i.nc
  hashes:
    binhash: 008ad863756d63d98bc66edbce1bc3ce
    md5: 90b1a5372b1e73292231448e0fbd6a2f
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/sicemass.nc
  hashes:
    binhash: e03d7016117fc03cafcc9b189f1d9b81
    md5: 2bd51faddab7d5fa7d1b9131ba497111
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ice/u_star.nc
  hashes:
    binhash: e386a6fbdebf9a704536ce7332cc8989
    md5: a6e823ac27924e925a4944e7ef593d50
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_age.res.nc
  hashes:
    binhash: 37c3c4b200474618af57739189158eb8
    md5: 4aa9b38fc1491b0b62993ad6df7e210e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9759bf103c087681e616cd317e676d04
    md5: 9f33fe2d5d38bc675886680d7b296477
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ff52cac986b2b3ec6fb538182487d9bf
    md5: 9fa02b47cefc24f9d5729bef9cb96755
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_density.res.nc
  hashes:
    binhash: 9a62214fa6f49d8fc707b0e5b3ac5731
    md5: 7a4477bc20d1814bb690ea0d4da62a9e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 72641bdd34010290204d39d8d9d75832
    md5: 4fe12ed990451fa1aeb819b60f712141
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 08a359dcb92d0e9cfa910e8234f70439
    md5: 7981c48b4c6e02b0a9667ab6957133f7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 52c76919334f9e9e7101a7eaf60d25b6
    md5: f81ded259143a1f329baac8baf0ddd20
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cd84a1b6d6ee6ca2dfb0261c3f4cfaac
    md5: 026335c93ab2f1e433b342d43686244c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 11166397922045ca76996fa59c7a1f9d
    md5: 468c962a98fdeb8de6b1e6f4caf1b7b0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bdc3bde9c4ca6bc7c992c1f9e3d08c26
    md5: 5d4398662c59474bb8d8fd1225d06cb6
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_solo.res
  hashes:
    binhash: 3125f90c81fb86442b85413fbb302a37
    md5: ce6faf1e366f633e663489e55f08c1ce
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f8fd3a61c5e5e0b474c7b87339d30b53
    md5: 513e0c38bc2c85e17a3f8997cf634f10
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 277a4cebb247b71812b3b3482da57332
    md5: 1eb1a3927ab5234b762d4f8f263c5e57
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_tracer.res
  hashes:
    binhash: cc0d0b42ba5494ea406590c57a32d6dc
    md5: ade5442373f56659819ce511d1efa1a3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_velocity.res.nc
  hashes:
    binhash: be890207d783bde459a50c4508a09d1a
    md5: 705aecffd338842c9b69555d50dbaf28
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/ic0706/access-om2/archive/1deg_era5_iaf_tas_053_uas_015_increase/restart021/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2a7ab1f4a1ca2012ba3bb6774fe9d34e
    md5: 2552489948b937a8a76469fab122246a
